# This is a basic workflow to help you get started with Actions

name: more_jobs


on:
   workflow_run:
      workflows: [greeting]
      types:
         -completed
         
   workflow_dispatch:

env:
  DAY_OF_WEEK: Monday
  First_Name: Hampus
  GREETING: Hello 
  secrets: ${{ secrets.SUPER_SECRET }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print current day
        run: echo "$GREETING $First_Name. Today is $DAY_OF_WEEK"
 
  job2:
   runs-on: ubuntu-latest
   steps:
      - name: Print dont like monday
        run: echo "$GREETING! $First_Name dont like $DAY_OF_WEEK. This is $secrets"
   needs: job1
